services:
  - type: web
    name: icoding-compute-it
    env: node
    buildCommand: npm install && vite build && esbuild server/production-index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --outfile=dist/index.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000